# 1.1 Scaling

## Contents
### 1. Importing data and libraries
### 2. Scaling
#### 2.1 Subset Data
#### 2.2 Check for missing values
#### 2.3 Scaling
### 3. Export Data

## 1. Importing data and libraries

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import os
import sklearn
from sklearn.preprocessing import StandardScaler

In [5]:
# Define pathname
path = r'/Users/sydneyjohnson/Documents/CF Data Analytics Course/11-2024 ClimateWins Analysis/02 Data'

In [7]:
df = pd.read_csv(os.path.join(path, 'Dataset-weather-prediction-dataset-processed.csv'))

In [9]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [11]:
df.shape

(22950, 170)

In [13]:
df.reset_index(inplace=True)
df.rename(columns={'index':'id'}, inplace=True)
df.head()

,id,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [47]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22950 entries, 0 to 22949
Data columns (total 171 columns):
 #    Column                       Non-Null Count  Dtype
---   ------                       --------------  -----
 0    id                           22950 non-null  int64
 1    DATE                         22950 non-null  int64
 2    MONTH                        22950 non-null  int64
 3    BASEL_cloud_cover            22950 non-null  int64
 4    BASEL_wind_speed             22950 non-null  float64
 5    BASEL_humidity               22950 non-null  float64
 6    BASEL_pressure               22950 non-null  float64
 7    BASEL_global_radiation       22950 non-null  float64
 8    BASEL_precipitation          22950 non-null  float64
 9    BASEL_snow_depth             22950 non-null  int64
 10   BASEL_sunshine               22950 non-null  float64
 11   BASEL_temp_mean              22950 non-null  float64
 12   BASEL_temp_min               22950 non-null  float64
 13   BASEL_temp_max               22950 non-null  float64
 14   BELGRADE_cloud_cover         22950 non-null  int64
 15   BELGRADE_humidity            22950 non-null  float64
 16   BELGRADE_pressure            22950 non-null  float64
 17   BELGRADE_global_radiation    22950 non-null  float64
 18   BELGRADE_precipitation       22950 non-null  float64
 19   BELGRADE_sunshine            22950 non-null  float64
 20   BELGRADE_temp_mean           22950 non-null  float64
 21   BELGRADE_temp_min            22950 non-null  float64
 22   BELGRADE_temp_max            22950 non-null  float64
 23   BUDAPEST_cloud_cover         22950 non-null  int64
 24   BUDAPEST_humidity            22950 non-null  float64
 25   BUDAPEST_pressure            22950 non-null  float64
 26   BUDAPEST_global_radiation    22950 non-null  float64
 27   BUDAPEST_precipitation       22950 non-null  float64
 28   BUDAPEST_sunshine            22950 non-null  float64
 29   BUDAPEST_temp_mean           22950 non-null  float64
 30   BUDAPEST_temp_min            22950 non-null  float64
 31   BUDAPEST_temp_max            22950 non-null  float64
 32   DEBILT_cloud_cover           22950 non-null  int64
 33   DEBILT_wind_speed            22950 non-null  float64
 34   DEBILT_humidity              22950 non-null  float64
 35   DEBILT_pressure              22950 non-null  float64
 36   DEBILT_global_radiation      22950 non-null  float64
 37   DEBILT_precipitation         22950 non-null  float64
 38   DEBILT_sunshine              22950 non-null  float64
 39   DEBILT_temp_mean             22950 non-null  float64
 40   DEBILT_temp_min              22950 non-null  float64
 41   DEBILT_temp_max              22950 non-null  float64
 42   DUSSELDORF_cloud_cover       22950 non-null  int64
 43   DUSSELDORF_wind_speed        22950 non-null  float64
 44   DUSSELDORF_humidity          22950 non-null  float64
 45   DUSSELDORF_pressure          22950 non-null  float64
 46   DUSSELDORF_global_radiation  22950 non-null  float64
 47   DUSSELDORF_precipitation     22950 non-null  float64
 48   DUSSELDORF_snow_depth        22950 non-null  int64
 49   DUSSELDORF_sunshine          22950 non-null  float64
 50   DUSSELDORF_temp_mean         22950 non-null  float64
 51   DUSSELDORF_temp_min          22950 non-null  float64
 52   DUSSELDORF_temp_max          22950 non-null  float64
 53   GDANSK_cloud_cover           22950 non-null  int64
 54   GDANSK_humidity              22950 non-null  float64
 55   GDANSK_precipitation         22950 non-null  float64
 56   GDANSK_snow_depth            22950 non-null  int64
 57   GDANSK_temp_mean             22950 non-null  float64
 58   GDANSK_temp_min              22950 non-null  float64
 59   GDANSK_temp_max              22950 non-null  float64
 60   HEATHROW_cloud_cover         22950 non-null  int64
 61   HEATHROW_humidity            22950 non-null  float64
 62   HEATHROW_pressure            22950 non-null  float64
 63   HEATHROW_global_radiation    22950 non-null  float64
 64   HEATHROW_precipitation       22950 non-null  float64
 65   HEATHROW_snow_depth          22950 non-null  int64
 66   HEATHROW_sunshine            22950 non-null  float64
 67   HEATHROW_temp_mean           22950 non-null  float64
 68   HEATHROW_temp_min            22950 non-null  float64
 69   HEATHROW_temp_max            22950 non-null  float64
 70   KASSEL_wind_speed            22950 non-null  float64
 71   KASSEL_humidity              22950 non-null  float64
 72   KASSEL_pressure              22950 non-null  float64
 73   KASSEL_global_radiation      22950 non-null  float64
 74   KASSEL_precipitation         22950 non-null  float64
 75   KASSEL_sunshine              22950 non-null  float64
 76   KASSEL_temp_mean             22950 non-null  float64
 77   KASSEL_temp_min              22950 non-null  float64
 78   KASSEL_temp_max              22950 non-null  float64
 79   LJUBLJANA_cloud_cover        22950 non-null  int64
 80   LJUBLJANA_wind_speed         22950 non-null  float64
 81   LJUBLJANA_humidity           22950 non-null  float64
 82   LJUBLJANA_pressure           22950 non-null  float64
 83   LJUBLJANA_global_radiation   22950 non-null  float64
 84   LJUBLJANA_precipitation      22950 non-null  float64
 85   LJUBLJANA_sunshine           22950 non-null  float64
 86   LJUBLJANA_temp_mean          22950 non-null  float64
 87   LJUBLJANA_temp_min           22950 non-null  float64
 88   LJUBLJANA_temp_max           22950 non-null  float64
 89   MAASTRICHT_cloud_cover       22950 non-null  int64
 90   MAASTRICHT_wind_speed        22950 non-null  float64
 91   MAASTRICHT_humidity          22950 non-null  float64
 92   MAASTRICHT_pressure          22950 non-null  float64
 93   MAASTRICHT_global_radiation  22950 non-null  float64
 94   MAASTRICHT_precipitation     22950 non-null  float64
 95   MAASTRICHT_sunshine          22950 non-null  float64
 96   MAASTRICHT_temp_mean         22950 non-null  float64
 97   MAASTRICHT_temp_min          22950 non-null  float64
 98   MAASTRICHT_temp_max          22950 non-null  float64
 99   MADRID_cloud_cover           22950 non-null  int64
 100  MADRID_wind_speed            22950 non-null  float64
 101  MADRID_humidity              22950 non-null  float64
 102  MADRID_pressure              22950 non-null  float64
 103  MADRID_global_radiation      22950 non-null  float64
 104  MADRID_precipitation         22950 non-null  float64
 105  MADRID_sunshine              22950 non-null  float64
 106  MADRID_temp_mean             22950 non-null  float64
 107  MADRID_temp_min              22950 non-null  float64
 108  MADRID_temp_max              22950 non-null  float64
 109  MUNCHENB_cloud_cover         22950 non-null  int64
 110  MUNCHENB_humidity            22950 non-null  float64
 111  MUNCHENB_global_radiation    22950 non-null  float64
 112  MUNCHENB_precipitation       22950 non-null  float64
 113  MUNCHENB_snow_depth          22950 non-null  int64
 114  MUNCHENB_sunshine            22950 non-null  float64
 115  MUNCHENB_temp_mean           22950 non-null  float64
 116  MUNCHENB_temp_min            22950 non-null  float64
 117  MUNCHENB_temp_max            22950 non-null  float64
 118  OSLO_cloud_cover             22950 non-null  int64
 119  OSLO_wind_speed              22950 non-null  float64
 120  OSLO_humidity                22950 non-null  float64
 121  OSLO_pressure                22950 non-null  float64
 122  OSLO_global_radiation        22950 non-null  float64
 123  OSLO_precipitation           22950 non-null  float64
 124  OSLO_snow_depth              22950 non-null  int64
 125  OSLO_sunshine                22950 non-null  float64
 126  OSLO_temp_mean               22950 non-null  float64
 127  OSLO_temp_min                22950 non-null  float64
 128  OSLO_temp_max                22950 non-null  float64
 129  ROMA_cloud_cover             22950 non-null  int64
 130  ROMA_wind_speed              22950 non-null  float64
 131  ROMA_humidity                22950 non-null  float64
 132  ROMA_pressure                22950 non-null  float64
 133  ROMA_sunshine                22950 non-null  float64
 134  ROMA_temp_mean               22950 non-null  float64
 135  SONNBLICK_cloud_cover        22950 non-null  int64
 136  SONNBLICK_wind_speed         22950 non-null  float64
 137  SONNBLICK_humidity           22950 non-null  float64
 138  SONNBLICK_pressure           22950 non-null  float64
 139  SONNBLICK_global_radiation   22950 non-null  float64
 140  SONNBLICK_precipitation      22950 non-null  float64
 141  SONNBLICK_sunshine           22950 non-null  float64
 142  SONNBLICK_temp_mean          22950 non-null  float64
 143  SONNBLICK_temp_min           22950 non-null  float64
 144  SONNBLICK_temp_max           22950 non-null  float64
 145  STOCKHOLM_cloud_cover        22950 non-null  int64
 146  STOCKHOLM_pressure           22950 non-null  float64
 147  STOCKHOLM_global_radiation   22950 non-null  float64
 148  STOCKHOLM_precipitation      22950 non-null  float64
 149  STOCKHOLM_sunshine           22950 non-null  float64
 150  STOCKHOLM_temp_mean          22950 non-null  float64
 151  STOCKHOLM_temp_min           22950 non-null  float64
 152  STOCKHOLM_temp_max           22950 non-null  float64
 153  TOURS_wind_speed             22950 non-null  float64
 154  TOURS_humidity               22950 non-null  float64
 155  TOURS_pressure               22950 non-null  float64
 156  TOURS_global_radiation       22950 non-null  float64
 157  TOURS_precipitation          22950 non-null  float64
 158  TOURS_temp_mean              22950 non-null  float64
 159  TOURS_temp_min               22950 non-null  float64
 160  TOURS_temp_max               22950 non-null  float64
 161  VALENTIA_cloud_cover         22950 non-null  int64
 162  VALENTIA_humidity            22950 non-null  float64
 163  VALENTIA_pressure            22950 non-null  float64
 164  VALENTIA_global_radiation    22950 non-null  float64
 165  VALENTIA_precipitation       22950 non-null  float64
 166  VALENTIA_snow_depth          22950 non-null  int64
 167  VALENTIA_sunshine            22950 non-null  float64
 168  VALENTIA_temp_mean           22950 non-null  float64
 169  VALENTIA_temp_min            22950 non-null  float64
 170  VALENTIA_temp_max            22950 non-null  float64
dtypes: float64(145), int64(26)
memory usage: 29.9 MB

In [55]:
print(df.columns.tolist())

['id', 'DATE', 'MONTH', 'BASEL_cloud_cover', 'BASEL_wind_speed', 'BASEL_humidity', 'BASEL_pressure', 'BASEL_global_radiation', 'BASEL_precipitation', 'BASEL_snow_depth', 'BASEL_sunshine', 'BASEL_temp_mean', 'BASEL_temp_min', 'BASEL_temp_max', 'BELGRADE_cloud_cover', 'BELGRADE_humidity', 'BELGRADE_pressure', 'BELGRADE_global_radiation', 'BELGRADE_precipitation', 'BELGRADE_sunshine', 'BELGRADE_temp_mean', 'BELGRADE_temp_min', 'BELGRADE_temp_max', 'BUDAPEST_cloud_cover', 'BUDAPEST_humidity', 'BUDAPEST_pressure', 'BUDAPEST_global_radiation', 'BUDAPEST_precipitation', 'BUDAPEST_sunshine', 'BUDAPEST_temp_mean', 'BUDAPEST_temp_min', 'BUDAPEST_temp_max', 'DEBILT_cloud_cover', 'DEBILT_wind_speed', 'DEBILT_humidity', 'DEBILT_pressure', 'DEBILT_global_radiation', 'DEBILT_precipitation', 'DEBILT_sunshine', 'DEBILT_temp_mean', 'DEBILT_temp_min', 'DEBILT_temp_max', 'DUSSELDORF_cloud_cover', 'DUSSELDORF_wind_speed', 'DUSSELDORF_humidity', 'DUSSELDORF_pressure', 'DUSSELDORF_global_radiation', 'DUSSELDORF_precipitation', 'DUSSELDORF_snow_depth', 'DUSSELDORF_sunshine', 'DUSSELDORF_temp_mean', 'DUSSELDORF_temp_min', 'DUSSELDORF_temp_max', 'GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation', 'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min', 'GDANSK_temp_max', 'HEATHROW_cloud_cover', 'HEATHROW_humidity', 'HEATHROW_pressure', 'HEATHROW_global_radiation', 'HEATHROW_precipitation', 'HEATHROW_snow_depth', 'HEATHROW_sunshine', 'HEATHROW_temp_mean', 'HEATHROW_temp_min', 'HEATHROW_temp_max', 'KASSEL_wind_speed', 'KASSEL_humidity', 'KASSEL_pressure', 'KASSEL_global_radiation', 'KASSEL_precipitation', 'KASSEL_sunshine', 'KASSEL_temp_mean', 'KASSEL_temp_min', 'KASSEL_temp_max', 'LJUBLJANA_cloud_cover', 'LJUBLJANA_wind_speed', 'LJUBLJANA_humidity', 'LJUBLJANA_pressure', 'LJUBLJANA_global_radiation', 'LJUBLJANA_precipitation', 'LJUBLJANA_sunshine', 'LJUBLJANA_temp_mean', 'LJUBLJANA_temp_min', 'LJUBLJANA_temp_max', 'MAASTRICHT_cloud_cover', 'MAASTRICHT_wind_speed', 'MAASTRICHT_humidity', 'MAASTRICHT_pressure', 'MAASTRICHT_global_radiation', 'MAASTRICHT_precipitation', 'MAASTRICHT_sunshine', 'MAASTRICHT_temp_mean', 'MAASTRICHT_temp_min', 'MAASTRICHT_temp_max', 'MADRID_cloud_cover', 'MADRID_wind_speed', 'MADRID_humidity', 'MADRID_pressure', 'MADRID_global_radiation', 'MADRID_precipitation', 'MADRID_sunshine', 'MADRID_temp_mean', 'MADRID_temp_min', 'MADRID_temp_max', 'MUNCHENB_cloud_cover', 'MUNCHENB_humidity', 'MUNCHENB_global_radiation', 'MUNCHENB_precipitation', 'MUNCHENB_snow_depth', 'MUNCHENB_sunshine', 'MUNCHENB_temp_mean', 'MUNCHENB_temp_min', 'MUNCHENB_temp_max', 'OSLO_cloud_cover', 'OSLO_wind_speed', 'OSLO_humidity', 'OSLO_pressure', 'OSLO_global_radiation', 'OSLO_precipitation', 'OSLO_snow_depth', 'OSLO_sunshine', 'OSLO_temp_mean', 'OSLO_temp_min', 'OSLO_temp_max', 'ROMA_cloud_cover', 'ROMA_wind_speed', 'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean', 'SONNBLICK_cloud_cover', 'SONNBLICK_wind_speed', 'SONNBLICK_humidity', 'SONNBLICK_pressure', 'SONNBLICK_global_radiation', 'SONNBLICK_precipitation', 'SONNBLICK_sunshine', 'SONNBLICK_temp_mean', 'SONNBLICK_temp_min', 'SONNBLICK_temp_max', 'STOCKHOLM_cloud_cover', 'STOCKHOLM_pressure', 'STOCKHOLM_global_radiation', 'STOCKHOLM_precipitation', 'STOCKHOLM_sunshine', 'STOCKHOLM_temp_mean', 'STOCKHOLM_temp_min', 'STOCKHOLM_temp_max', 'TOURS_wind_speed', 'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max', 'VALENTIA_cloud_cover', 'VALENTIA_humidity', 'VALENTIA_pressure', 'VALENTIA_global_radiation', 'VALENTIA_precipitation', 'VALENTIA_snow_depth', 'VALENTIA_sunshine', 'VALENTIA_temp_mean', 'VALENTIA_temp_min', 'VALENTIA_temp_max']

## 2. Scaling

### 2.1 Subset temperature data

In [57]:
#identify the useful numeric columns on temperature
columns = ['BASEL_temp_mean', 'BASEL_temp_min', 'BASEL_temp_max',
           'BELGRADE_temp_mean', 'BELGRADE_temp_min', 'BELGRADE_temp_max',
           'BUDAPEST_temp_mean', 'BUDAPEST_temp_min', 'BUDAPEST_temp_max',
           'DEBILT_temp_mean', 'DEBILT_temp_min', 'DEBILT_temp_max',
           'DUSSELDORF_temp_mean', 'DUSSELDORF_temp_min', 'DUSSELDORF_temp_max',
           'GDANSK_temp_mean', 'GDANSK_temp_min', 'GDANSK_temp_max',
           'HEATHROW_temp_mean', 'HEATHROW_temp_min', 'HEATHROW_temp_max',
           'KASSEL_temp_mean', 'KASSEL_temp_min', 'KASSEL_temp_max',
           'LJUBLJANA_temp_mean', 'LJUBLJANA_temp_min', 'LJUBLJANA_temp_max',
           'MAASTRICHT_temp_mean', 'MAASTRICHT_temp_min', 'MAASTRICHT_temp_max',
           'MADRID_temp_mean', 'MADRID_temp_min', 'MADRID_temp_max',
           'MUNCHENB_temp_mean', 'MUNCHENB_temp_min', 'MUNCHENB_temp_max',
           'OSLO_temp_mean', 'OSLO_temp_min', 'OSLO_temp_max',
           'ROMA_temp_mean',
           'SONNBLICK_temp_mean', 'SONNBLICK_temp_min', 'SONNBLICK_temp_max',
           'STOCKHOLM_temp_mean', 'STOCKHOLM_temp_min', 'STOCKHOLM_temp_max',
           'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max',
           'VALENTIA_temp_mean', 'VALENTIA_temp_min', 'VALENTIA_temp_max']

#### Dataset is missing columns for ROMA_temp_min and ROMA_temp_max

In [60]:
df_temp = df[columns]
df_temp.head()

,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_temp_mean,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,6.5,0.8,10.9,3.7,-0.9,7.9,2.4,-0.4,5.1,9.3,7.4,11.0,10.0,7.0,11.5,0.8,-0.3,1.6,10.6,9.4,8.3,7.9,3.9,9.4,-0.6,-1.9,0.5,9.5,8.5,11.1,7.6,4.4,10.8,6.9,1.1,10.4,4.9,3.8,5.9,7.8,-5.9,-8.5,-3.2,4.2,2.2,4.9,10.0,7.8,12.2,8.5,6.0,10.9
1,6.1,3.3,10.1,2.9,2.2,4.4,2.3,1.4,3.1,7.7,6.4,8.3,8.2,7.4,11.0,1.6,0.9,2.2,6.1,3.9,10.6,7.7,6.8,9.1,2.1,-1.3,5.5,8.6,7.5,9.9,9.8,7.4,12.2,6.2,4.2,10.2,3.4,2.8,4.9,12.2,-9.5,-10.5,-8.5,4.0,3.0,5.0,9.5,7.0,12.0,8.9,5.6,12.1
2,8.5,5.1,9.9,3.1,-0.5,6.4,2.7,1.7,5.3,6.8,4.6,9.9,7.1,6.9,9.1,0.7,0.4,1.7,8.4,6.1,12.2,6.5,6.0,8.0,4.6,0.9,6.3,6.9,5.5,9.9,8.6,6.4,10.8,5.8,4.0,8.0,1.9,0.6,3.1,10.2,-9.5,-10.0,-8.9,2.4,1.3,4.1,10.3,9.0,11.6,10.5,8.1,12.9
3,6.3,3.8,10.6,2.0,-2.0,3.0,2.0,0.4,4.4,6.7,3.6,10.1,6.8,3.6,8.0,-0.1,-0.9,2.0,9.4,6.7,8.9,5.8,5.2,6.5,3.2,1.0,7.0,7.0,3.0,10.0,10.3,4.5,16.1,3.9,3.2,5.4,3.0,0.4,4.9,10.8,-11.5,-12.9,-10.0,1.2,0.4,2.3,11.2,9.9,12.6,7.4,7.3,10.6
4,3.0,-0.7,6.0,2.0,0.7,2.8,2.5,1.1,5.3,8.0,2.4,11.2,7.7,6.2,11.0,0.4,-1.7,1.5,8.9,8.9,7.2,5.4,3.7,6.0,3.6,0.4,4.8,8.1,2.5,11.1,12.1,8.2,16.0,1.8,-3.0,6.0,3.7,2.9,4.9,9.9,-9.3,-12.0,-6.5,3.3,0.8,4.3,11.4,10.7,12.0,5.7,3.0,8.4

In [62]:
### 2.2 Check for missing values
df_temp.isnull().sum()

BASEL_temp_mean         0
BASEL_temp_min          0
BASEL_temp_max          0
BELGRADE_temp_mean      0
BELGRADE_temp_min       0
BELGRADE_temp_max       0
BUDAPEST_temp_mean      0
BUDAPEST_temp_min       0
BUDAPEST_temp_max       0
DEBILT_temp_mean        0
DEBILT_temp_min         0
DEBILT_temp_max         0
DUSSELDORF_temp_mean    0
DUSSELDORF_temp_min     0
DUSSELDORF_temp_max     0
GDANSK_temp_mean        0
GDANSK_temp_min         0
GDANSK_temp_max         0
HEATHROW_temp_mean      0
HEATHROW_temp_min       0
HEATHROW_temp_max       0
KASSEL_temp_mean        0
KASSEL_temp_min         0
KASSEL_temp_max         0
LJUBLJANA_temp_mean     0
LJUBLJANA_temp_min      0
LJUBLJANA_temp_max      0
MAASTRICHT_temp_mean    0
MAASTRICHT_temp_min     0
MAASTRICHT_temp_max     0
MADRID_temp_mean        0
MADRID_temp_min         0
MADRID_temp_max         0
MUNCHENB_temp_mean      0
MUNCHENB_temp_min       0
MUNCHENB_temp_max       0
OSLO_temp_mean          0
OSLO_temp_min           0
OSLO_temp_max           0
ROMA_temp_mean          0
SONNBLICK_temp_mean     0
SONNBLICK_temp_min      0
SONNBLICK_temp_max      0
STOCKHOLM_temp_mean     0
STOCKHOLM_temp_min      0
STOCKHOLM_temp_max      0
TOURS_temp_mean         0
TOURS_temp_min          0
TOURS_temp_max          0
VALENTIA_temp_mean      0
VALENTIA_temp_min       0
VALENTIA_temp_max       0
dtype: int64

#### No nulls

### 2.3 Scaling

In [66]:
#create scaler object using StandardScaler from sklearn.preprocessing
scaler = StandardScaler()

In [70]:
#create new df with scaled data

df_temp_scaled = pd.DataFrame(scaler.fit_transform(df_temp), columns=columns)
df_temp_scaled.head()

,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_temp_mean,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,-0.528623,-0.845652,-0.478356,-1.016876,-1.220210,-0.949203,-1.099163,-1.119431,-1.136839,-0.114356,0.263326,-0.411047,-0.105836,0.060555,-0.410423,-0.927601,-0.667864,-1.158624,-0.106469,0.393470,-1.038492,-0.182904,-0.251893,-0.466503,-1.370824,-1.125110,-1.578385,-0.097084,0.382899,-0.387967,-0.988280,-0.877723,-1.044732,-0.265742,-0.505735,-0.350849,-0.186575,0.094958,-0.474865,-1.280450,-0.124331,-0.170125,-0.063322,-0.391072,-0.290439,-0.639538,-0.257321,0.085361,-0.495396,-0.668215,-0.519743,-0.752237
1,-0.582946,-0.462450,-0.569988,-1.107669,-0.818702,-1.298119,-1.110927,-0.878727,-1.341204,-0.367511,0.090631,-0.781002,-0.370915,0.125463,-0.473486,-0.825294,-0.506386,-1.089557,-0.892676,-0.639866,-0.687774,-0.212437,0.231491,-0.504162,-1.043881,-1.043446,-1.056415,-0.232112,0.216034,-0.542607,-0.691740,-0.411866,-0.882444,-0.353714,-0.076441,-0.372683,-0.368598,-0.033545,-0.582847,-0.539569,-0.650834,-0.456455,-0.839563,-0.415953,-0.183610,-0.628550,-0.335759,-0.056680,-0.521727,-0.548046,-0.629054,-0.407141
2,-0.257010,-0.186545,-0.592896,-1.084971,-1.168403,-1.098738,-1.063873,-0.838610,-1.116403,-0.509912,-0.220221,-0.561770,-0.532908,0.044328,-0.713127,-0.940389,-0.573669,-1.147113,-0.490837,-0.226532,-0.443796,-0.389635,0.098144,-0.642248,-0.741156,-0.744013,-0.972900,-0.487164,-0.117697,-0.542607,-0.853490,-0.567152,-1.044732,-0.403983,-0.104138,-0.612852,-0.550620,-0.316251,-0.777215,-0.876333,-0.650834,-0.384873,-0.898147,-0.615003,-0.410621,-0.727444,-0.210258,0.298424,-0.574390,-0.067372,0.054135,-0.177078
3,-0.555784,-0.385810,-0.512718,-1.209812,-1.362681,-1.437685,-1.146217,-1.012452,-1.208367,-0.525734,-0.392916,-0.534366,-0.577088,-0.491160,-0.851866,-1.042696,-0.748602,-1.112579,-0.316124,-0.113804,-0.947000,-0.493001,-0.035203,-0.830547,-0.910682,-0.730403,-0.899824,-0.472161,-0.534861,-0.529720,-0.624345,-0.862194,-0.430357,-0.642763,-0.214923,-0.896689,-0.417137,-0.341951,-0.582847,-0.775304,-0.943336,-0.800052,-1.059254,-0.764290,-0.530804,-0.925231,-0.069069,0.458220,-0.442733,-0.998679,-0.164486,-0.838511
4,-1.003946,-1.075573,-1.039603,-1.209812,-1.012980,-1.457623,-1.087400,-0.918844,-1.116403,-0.320045,-0.600150,-0.383643,-0.444548,-0.069260,-0.473486,-0.978754,-0.856254,-1.170135,-0.403481,0.299530,-1.206227,-0.552067,-0.285230,-0.893313,-0.862246,-0.812066,-1.129491,-0.307127,-0.618294,-0.387967,-0.381721,-0.287638,-0.441949,-0.906678,-1.073511,-0.831188,-0.332193,-0.020694,-0.582847,-0.926848,-0.621584,-0.671203,-0.546642,-0.503037,-0.477389,-0.705467,-0.037694,0.600262,-0.521727,-1.509396,-1.339569,-1.471186

## 3. Export Data

In [76]:
# Export scaled temperature data
df_temp_scaled.to_pickle(os.path.join(path, 'temp_scaled.pkl'))